version: '3.8'

services:
  # -----------------------------------------------------
  # 1. MongoDB
  # -----------------------------------------------------
  mongo:
    image: mongo:6.0
    container_name: mongo
    ports:
      - "27017:27017"


    volumes:
      - mongo-data:/data/db

  # -----------------------------------------------------
  # 2. RabbitMQ
  # -----------------------------------------------------
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"   # AMQP protocol
      - "15672:15672" # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      start_period: 45s
      retries: 5

  # -----------------------------------------------------
  # 3. User Service
  # -----------------------------------------------------
  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    container_name: foodfast-user-service
    restart: always
    ports:
      - "4000:4000"
    environment:
      PORT: 4000
      MONGO_URI: mongodb://mongo:27017/users_db
      JWT_SECRET: secret123
    depends_on:
      mongo:
        condition: service_started

  # -----------------------------------------------------
  # 4. Product Service
  # -----------------------------------------------------
  product-service:
    build:
      context: ./product-service
      dockerfile: Dockerfile
    container_name: foodfast-product-service
    restart: always
    ports:
      - "4001:4001"
    environment:
      PORT: 4001
      MONGO_URI: mongodb://mongo:27017/products_db
    depends_on:
      mongo:
        condition: service_started

  # -----------------------------------------------------
  # 5. Payment Service
  # -----------------------------------------------------
  payment-service:
    build:
      context: ./payment-service
      dockerfile: Dockerfile
    container_name: foodfast-payment-service
    restart: always
    ports:
      - "4002:4002"
    environment:
      PORT: 4002
      MONGO_URI: mongodb://mongo:27017/payments_db
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672
    depends_on:
      mongo:
        condition: service_started
      rabbitmq:
        condition: service_healthy

  # -----------------------------------------------------
  # 6. Order Service
  # -----------------------------------------------------
  order-service:
    build:
      context: ./order-service
      dockerfile: Dockerfile
    container_name: foodfast-order-service
    restart: always
    ports:
      - "4003:4003"
    environment:
      PORT: 4003
      MONGO_URI: mongodb://mongo:27017/orders_db
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672
    depends_on:
      mongo:
        condition: service_started
      rabbitmq:
        condition: service_healthy

volumes:
  mongo-data:
